Repository Fancy96/useless-coin-pick, pull requests merged in 2023-05, with the labels that each got.

#5 feat: footer 레이아웃 구현
  main/main.css
  main/main.html
Labels: feature, FE

#8 [Chore] PR template를 작성한다.
  .github/PUL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: docs

#9 [Feat] header 레이아웃 구현
  main/main.css
  main/main.html
  media/header_img.png
Labels: feature, FE

#10 [Feat] slot_machine 레이아웃 완성
  main/main.css
  main/main.html
Labels: feature, FE

#11 [Feat] 메인페이지 추천리스트 레이아웃 구현
  img/coin_footer.png
  img/coin_header.png
  img/coin_list.png
  img/coin_slot_machine.png
  main/main.css
  main/main.html
Labels: feature, FE

#13 [Feat] 팝업창 화면 기능 구현
  main/main.css
  main/main.html
  main/main.js
  popup/popup.css
  popup/popup.html
Labels: feature, FE

#14 [Chore] PR 템플릿 이름 수정
  .github/ISSUE_TEMPLATE/feature-issues-템플릿.md
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST_TEMPLATE.md
  README.md
  intro/introduce.css
  intro/introduce.html
  intro/introduce.js
  main/home.css
  main/home.html
  main/home.js
Labels: docs, fix

#16 [Feat] main 페이지의 코인 슬롯 머신에 레버 구현 및 팝업창 이미지 넣기
  main/main.css
  main/main.html
  main/main.js
  media/popup_img.jpg
  popup/popup.css
  popup/popup.html
Labels: feature, FE

#18 Feature/12
  upbitAPI/.vscode/settings.json
  upbitAPI/coin.html
  upbitAPI/coin.js
  upbitAPI/package-lock.json
  upbitAPI/package.json
  upbitAPI/upbit.js
Labels: feature, refactor, BE

#20 [feat] 코인 슬롯 머신 페이지와 api 연동
  .vscode/settings.json
  backup.js
  main/main.html
  upbitAPI/coin.js
Labels: feature, BE

#21 [Feat] 메인페이지 css변경
  main/main.css
  main/main.html
Labels: feature, FE

#25 [Feat]:메인 페이지 코인 종목명과 가격을 List로 출력한다.
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/useless-coin-pick.iml
  .idea/vcs.xml
  main/main.css
  main/main.html
  main/main.js
  upbitAPI/coin.js
Labels: feature, BE, FE

#27 [Refactor] 기존 코드에서 프론트엔드 코드 작성 규칙을 적용
  main/main.css
  main/main.html
  main/main.js
  upbitAPI/coin.js
Labels: refactor, BE, FE

#31 [chore] Update README.md
  README.md
Labels: docs

#33 [Refactor] 메인 페이지에 있는 슬롯 머신 게임, 코인 리스트 구현한 코드 설명을 위한 주석 추가
  main/main.js
  upbitAPI/coin.js
Labels: refactor, BE

#35 [Chore] 폴더 위치 변경
  backend/upbitAPI/.vscode/settings.json
  backend/upbitAPI/coin.html
  backend/upbitAPI/coin.js
  backend/upbitAPI/package-lock.json
  backend/upbitAPI/package.json
  backend/upbitAPI/upbit.js
  frontend/img/coin_footer.png
  frontend/img/coin_header.png
  frontend/img/coin_list.png
  frontend/img/coin_slot_machine.png
  frontend/img/completed.png
  frontend/img/completed_2.png
  frontend/img/css.png
  frontend/img/heroku.png
  frontend/img/html.png
  frontend/img/javascript.png
  frontend/img/lighthouse.png
  frontend/img/readme.jpeg
  frontend/main/main.css
  frontend/main/main.html
  frontend/main/main.js
  frontend/media/header_img.png
  frontend/media/popup_img.jpg
  frontend/popup/popup.css
  frontend/popup/popup.html
  intro/intro.css
  intro/intro.html
  intro/intro.js
  main2.js
Labels: docs

#37 [Docs] README.md 및 파일 경로 수정
  .gitignore
  README.md
  backend/upbitAPI/.vscode/settings.json
  backend/upbitAPI/coin.html
  backend/upbitAPI/coin.js
  backend/upbitAPI/package-lock.json
  backend/upbitAPI/package.json
  backend/upbitAPI/upbit.js
  frontend/img/coin_footer.png
  frontend/img/coin_header.png
  frontend/img/coin_list.png
  frontend/img/coin_slot_machine.png
  frontend/img/completed.png
  frontend/img/completed_2.png
  frontend/img/css.png
  frontend/img/heroku.png
  frontend/img/html.png
  frontend/img/javascript.png
  frontend/img/lighthouse.png
  frontend/img/tech_stack.jpeg
  frontend/main/main.css
  frontend/main/main.html
  frontend/main/main.js
  frontend/media/header_img.png
  frontend/media/popup_img.jpg
  frontend/popup/popup.css
  frontend/popup/popup.html
  intro/intro.css
  intro/intro.html
  intro/intro.js
  main/main.js
  main2.js
Labels: docs
